### ISSUE TITLE
Destroying a bridge with requests ongoing

### ISSUE THREAD

**Issue by andrewc910** [angeljruiz/BridgeAPI.rb#29]
I haven't tested this but if this seems like it could cause a nasty bug. Events would be deleted but the jobs wouldn't. This would result in sidekiq passing in an event id that no longer exists. Jobs would sort themselves out after enough retries but i think it would be best to check if any jobs are not completed and prevent deletion until they are. Thoughts?

**Comment by williampj** [comment]
Otherwise each uncompleted event could call the EventController#abort action that Angel is working on, which is meant to kill all current sidekiq jobs.

**Comment by angeljruiz** [comment]
We're now returning immediately based on a conditional in EventWorker's `perform`. We could also return if no event is found, which I believe would solve this issue. Ghost events would still be in the queue if a bridge is deleted, but they'd immediately sort themselves out once executed

**Comment by andrewc910** [comment]
@angeljruiz Perfect, implement that and ping me when its done.
